### ISSUE TITLE
bf_switchd Takes Longer to Launch on mion

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/meta-mion-sde#13]
Comparing the intialisation of `bf_swithd` on both _mion_ and _Ubuntu_ installs reveals that the startup process takes considerably longer on _mion_.

**Comment by CommitThis** [comment]
`strace` indicated that the SDE spins on opening and closing firmware files, specifically `serdes_B0.rom`. It spends about 33 seconds on this :grimacing:

The difference between the _mion_ installation and our reference Ubuntu install is that _mion_ has a lot more binaries installed, and it appears as though symlinks were copied to the rootfs but dereferenced in the process (so no symlinks exist on the target in this regard).

**Comment by johntoomey** [comment]
Tested and working on a BF2556X-1T
