### ISSUE TITLE
Add `${SDE_INSTALL}` to `env`

### ISSUE THREAD

**Issue by CommitThis** [NetworkGradeLinux/meta-mion-sde#32]
It would be useful if the SDE_INSTALL environment variable was populated. This would save me an export for the webinar :)

**Comment by toganlabs** [comment]
Fixed in https://github.com/NetworkGradeLinux/meta-mion-sde/pull/34

**Comment by toganlabs** [comment]
Rather fixed in https://github.com/NetworkGradeLinux/meta-mion-sde/pull/34/commits/4f604e63068c7eac21b4646dfc7f1d8b313376d6
